/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Lavadora(props) {
  const { nodes, materials } = useGLTF('/models-3d/Lavadora.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.051} position={[20, -16.8, -15]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BOSCH_WLG_1.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BOSCH_WLG_2.geometry}
          material={materials.wire_087225087}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BOSCH_WLG_3.geometry}
          material={materials.wire_088144225}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BOSCH_WLG_4.geometry}
          material={materials.wire_213154229}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BOSCH_WLG_5.geometry}
          material={materials.wire_028089177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BOSCH_WLG_6.geometry}
          material={materials.wire_057008136}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BOSCH_WLG_7.geometry}
          material={materials.wire_085028177}
        />
      </group>
    </group>
  )
}

export default Lavadora;
useGLTF.preload('/models-3d/Lavadora.glb')