/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Pancito(props) {
  const { nodes, materials } = useGLTF('/models-3d/Pancito.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
       position={[3, 2, -4]}
        castShadow
        receiveShadow
        geometry={nodes.DrawCall_85.geometry}
        material={materials.Material}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

export default Pancito;
useGLTF.preload('/models-3d/Pancito.glb')