/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function TeclaS(props) {
  const { nodes, materials } = useGLTF("/models-3d/TeclaS.glb");
  if (materials["ser klav"]) {
    materials["ser klav"].color.set("#ffffff");
  }

  return (
    <group
      {...props}
      dispose={null}
      position={[1, 0, -1]}
      rotation={[Math.PI / 2, 1.5, 0]}
      scale={0.8}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube083.geometry}
        material={materials["ser klav"]}
        position={[0.179, 0.264, 0.804]}
        rotation={[0, 0, 0.017]}
        scale={0.053}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube078.geometry}
        material={materials["ser klav"]}
        position={[-0.151, 0.258, 0.915]}
        rotation={[0, 0, 0.017]}
        scale={0.053}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube077.geometry}
        material={materials["ser klav"]}
        position={[-0.261, 0.257, 1.024]}
        rotation={[0, 0, 0.017]}
        scale={0.053}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube076.geometry}
        material={materials["ser klav"]}
        position={[-0.261, 0.257, 0.804]}
        rotation={[0, 0, 0.017]}
        scale={0.053}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube075.geometry}
        material={materials["ser klav"]}
        position={[-0.261, 0.257, 0.914]}
        rotation={[0, 0, 0.017]}
        scale={0.053}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube074.geometry}
        material={materials["klav bel"]}
        position={[-0.261, 0.256, 0.141]}
        rotation={[0, 0, 0.017]}
        scale={[0.053, 0.053, 0.045]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube073.geometry}
        material={materials["ser klav"]}
        position={[-0.261, 0.256, 0.272]}
        rotation={[0, 0, 0.017]}
        scale={[0.053, 0.053, 0.045]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube072.geometry}
        material={materials["ser klav"]}
        position={[-0.261, 0.256, 0.404]}
        rotation={[0, 0, 0.017]}
        scale={[0.053, 0.053, 0.045]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube071.geometry}
        material={materials["ser klav"]}
        position={[-0.261, 0.256, 0.535]}
        rotation={[0, 0, 0.017]}
        scale={[0.053, 0.053, 0.045]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube070.geometry}
        material={materials["ser klav"]}
        position={[-0.261, 0.256, 0.667]}
        rotation={[0, 0, 0.017]}
        scale={[0.053, 0.053, 0.045]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube069.geometry}
        material={materials["ser klav"]}
        position={[-0.261, 0.256, -0.589]}
        rotation={[0, 0, 0.017]}
        scale={[0.053, 0.053, 0.045]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube068.geometry}
        material={materials["ser klav"]}
        position={[-0.261, 0.256, -0.72]}
        rotation={[0, 0, 0.017]}
        scale={[0.053, 0.053, 0.045]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube067.geometry}
        material={materials["ser klav"]}
        position={[-0.261, 0.256, -0.851]}
        rotation={[0, 0, 0.017]}
        scale={[0.053, 0.053, 0.045]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube066.geometry}
        material={materials["ser klav"]}
        position={[-0.151, 0.258, 0.46]}
        rotation={[0, 0, 0.017]}
        scale={0.053}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube065.geometry}
        material={materials["ser klav"]}
        position={[-0.151, 0.258, -0.836]}
        rotation={[0, 0, 0.017]}
        scale={0.053}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube054.geometry}
        material={materials["ser klav"]}
        position={[0.069, 0.262, 0.594]}
        rotation={[0, 0, 0.017]}
        scale={0.053}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube053.geometry}
        material={materials["ser klav"]}
        position={[-0.041, 0.26, -0.836]}
        rotation={[0, 0, 0.017]}
        scale={0.053}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube041.geometry}
        material={materials["ser klav"]}
        position={[0.069, 0.262, -0.836]}
        rotation={[0, 0, 0.017]}
        scale={0.053}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube028.geometry}
        material={materials.Material}
        position={[-0.041, 0.264, -0.58]}
        rotation={[0, 0, 0.017]}
        scale={0.053}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={materials["ser klav"]}
        position={[0.309, 0.266, 0.651]}
        rotation={[0, 0, 0.017]}
        scale={0.053}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={materials["ser klav"]}
        position={[0.309, 0.266, 0.541]}
        rotation={[0, 0, 0.017]}
        scale={0.053}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={materials["ser klav"]}
        position={[0.309, 0.266, 0.431]}
        rotation={[0, 0, 0.017]}
        scale={0.053}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials["ser klav"]}
        position={[0.309, 0.266, 0.321]}
        rotation={[0, 0, 0.017]}
        scale={0.053}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials["ser klav"]}
        position={[0.309, 0.266, 0.148]}
        rotation={[0, 0, 0.017]}
        scale={0.053}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials["ser klav"]}
        position={[0.309, 0.266, 0.038]}
        rotation={[0, 0, 0.017]}
        scale={0.053}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials["ser klav"]}
        position={[0.309, 0.266, -0.072]}
        rotation={[0, 0, 0.017]}
        scale={0.053}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials["ser klav"]}
        position={[0.309, 0.266, -0.182]}
        rotation={[0, 0, 0.017]}
        scale={0.053}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials["ser klav"]}
        position={[0.309, 0.266, -0.375]}
        rotation={[0, 0, 0.017]}
        scale={0.053}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials["ser klav"]}
        position={[0.309, 0.266, -0.485]}
        rotation={[0, 0, 0.017]}
        scale={0.053}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials["ser klav"]}
        position={[0.309, 0.266, -0.595]}
        rotation={[0, 0, 0.017]}
        scale={0.053}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials["ser klav"]}
        position={[0.309, 0.266, -0.705]}
        rotation={[0, 0, 0.017]}
        scale={0.053}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials["ser klav"]}
        position={[0.309, 0.266, -0.886]}
        rotation={[0, 0, 0.017]}
        scale={0.053}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.klaviatura}
        position={[0, 0.2, 0]}
        scale={[0.354, 0.233, 1]}
      />
    </group>
  );
}

export default TeclaS;
useGLTF.preload("/models-3d/TeclaS.glb");
